Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - '**/Gemfile'

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
