alias ls='ls -G'
alias ll='ls -alG'
alias hgr='h | grep'
alias st='subl -n'
alias tigs='tig status'

alias be='bundle exec'
alias bi='bundle install'
alias brc='be rails c'
alias brs='be rails s'
alias brdc='be rake db:create'
alias brdm='be rake db:migrate'
alias brt='be rake test'
alias bfs='be foreman start'
